#!/bin/bash

#Description:We are going to create a Password Generator using Alphanumerics + Characters
#Length is going to be 8 characters, Random Number + Alphabet

# Initialize an empty password
Password=""

# Define the set of allowed characters
chars="A-Za-z0-9@#%&*"

# Function to generate random alphanumeric + special characters
generate_random_char() {
  echo $(< /dev/urandom tr -dc "$chars" | head -c1)
}

# Generate a password of 8 characters
for ((i = 0; i < 8; i++)); do
  Password+=$(generate_random_char)
done

# Output the generated password
echo "The new password for you is $Password"

# Calculate the length of the password
Plength=${#Password}

# Output the password length
echo "Password length is $Plength"

# Check if the password length is less than 8 (it should not be, given the loop above)
if ((Plength < 8)); then
  a=$((8 - Plength))
  echo "Password length is short of $a"
else
  echo "Password length is good"
fi
