#!/bin/bash

#Simple 8 digit password 

#!/bin/bash

# Generate a random password with 8 characters
password=$(tr -dc "A-Za-z0-9" < /dev/urandom | head -c 8)

# Display it

echo "New password for you: $password"
